service: cron-service

provider:
  name: aws
  runtime: python3.6
  region: eu-central-1
functions:
  hello:
    handler: handler.hello
    events:
      - schedule:
          rate: cron(*/15 * * * ? *)
          enabled: true
